version: "3.9"
services:
  db:
    image: mariadb:10.9
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db

  php:
    build:
      context: "./docker/php"
      dockerfile: "Dockerfile"
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./docker/php/conf.d/${ENVIRONMENT}.php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./docker/php/var/php-error.log:/var/log/php/php-error.log
      - ./src:/var/www/html
      - ./docker/bedrock/.env.${ENVIRONMENT}:/var/www/html/.env
      - ./docker/wordpress/scripts:/var/tmp/scripts
      - ./theme:/var/www/html/web/app/themes/{THEME_NAME}
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./docker/nginx/conf.d/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ./docker/bedrock/.env.${ENVIRONMENT}:/var/www/html/.env
      - ./docker/wordpress/scripts:/var/tmp/scripts
      - ./theme:/var/www/html/web/app/themes/${THEME_NAME}
    ports:
      - 80:80
    depends_on:
      - php
    restart: always

volumes:
  php-fpm-socket:
